package main

var (
	strGET           = []byte(`GET`)
	strPOST          = []byte(`POST`)
	strContentLength = []byte(`content-length`)
	strConnection    = []byte(`connection`)
	strClose         = []byte(`close`)
	strKeepAlive     = []byte(`keep-alive`)
	str11            = []byte(`/1.1`)

	line200 = []byte("HTTP/1.1 200 OK\r\n")
	line400 = []byte("HTTP/1.1 400 Bad Request\r\n")
	line404 = []byte("HTTP/1.1 404 Not Found\r\n")
	line500 = []byte("HTTP/1.1 500 Internal Server Error\r\n")

	emptyResponseBody = []byte(`{}`)
	strUsers          = []byte(`users`)
	strVisits         = []byte(`visits`)
	strLocations      = []byte(`locations`)
	strAvg            = []byte(`avg`)
	strNew            = []byte(`new`)

	strId         = []byte(`id`)
	strLocation   = []byte(`location`)
	strUser       = []byte(`user`)
	strVisitedAt  = []byte(`visited_at`)
	strMark       = []byte(`mark`)
	strPlace      = []byte(`place`)
	strCountry    = []byte(`country`)
	strCity       = []byte(`city`)
	strDistance   = []byte(`distance`)
	strEmail      = []byte(`email`)
	strFirstName  = []byte(`first_name`)
	strLastName   = []byte(`last_name`)
	strGender     = []byte(`gender`)
	strBirthdate  = []byte(`birth_date`)
	strFromDate   = []byte(`fromDate`)
	strToDate     = []byte(`toDate`)
	strToDistance = []byte(`toDistance`)
	strFromAge    = []byte(`fromAge`)
	strToAge      = []byte(`toAge`)
)
